# The `include` settings customize every feature that appears on plotted images by default (e.g. a mask, the
# coordinate system's origin, etc.).

# For example, if `include_2d -> mask:true`, the mask will not be plotted on any applicable figure by default.

include_1d:
  mask: false                       # Include a Mask ?
  origin: false                     # Include the (x,) origin of the data's coordinate system ?
  einstein_radius: true
  half_light_radius: true
include_2d:
  mask: true                        # Include a mask ?
  origin: false                     # Include the (y,x) origin of the data's coordinate system ?
  border: false                      # Include the border of the mask (all pixels on the outside of the mask) ?
  grid: false                       # Include the data's 2D grid of (y,x) coordinates ?
  positions: true                   # Include (y,x) coordinates specified via `Visuals2d.positions` ?
  tangential_critical_curves: true
  tangential_caustics: true
  radial_critical_curves: true
  radial_caustics: true
  light_profile_centres: false
  mass_profile_centres: false
  multiple_images: true
  mapper_image_plane_mesh_grid: false       # For an Inversion, include the pixel centres computed in the image-plane / data frame?
  mapper_source_plane_data_grid: false    # For an Inversion, include the centres of the image-plane grid mapped to the source-plane / frame in source-plane figures?
  mapper_source_plane_mesh_grid: false    # For an Inversion, include the centres of the mesh pixels in the source-plane / source-plane?
